### ISSUE TITLE
Cannot download artifacts from secured repository

### ISSUE THREAD

**Issue by martin-kvasnicka** [advanced-security/maven-dependency-submission-action#12]
We use our private repository for storing internal artifacts. When using maven-dependency-submission-action, it is not able to download them: status: 401 Unauthorized. I am providing correct token as input parameter (it works with other actions accessing the repository)

**Comment by mirzaprangon** [comment]
You can update the settings.xml inside the action to access the private repositories, using [maven-settings-xml-action](https://github.com/whelk-io/maven-settings-xml-action). I use this in my organization. Below example gets the private repository credentials from github secrets.
```yaml
jobs:
  # Dependency submission
  build_and_upload_to_release:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_USERNAME_1: ${{ secrets.REPOSITORY_USERNAME_1 }}
      REPOSITORY_TOKEN_PASS_1: ${{ secrets.REPOSITORY_TOKEN_PASS_1 }}
      REPOSITORY_USERNAME_2: ${{ secrets.REPOSITORY_USERNAME_2 }}
      REPOSITORY_TOKEN_PASS_2: ${{ secrets.REPOSITORY_TOKEN_PASS_2 }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 8 with maven cache
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    # Edit/create settings.xml to enable maven to access the private repositories
    - name: Set up maven config in settings.xml
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: |
          [
            { "id": "central", "url": "https://repo1.maven.org/maven2" },
            { "id": "private_repository_1", "url": "https://somerepository1.com/repo1" },
            { "id": "private_repository_2", "url": "https://somerepository2.com/repo2" }
          ]
        servers: |
          [
            { "id": "private_repository_1", "username": "${env.REPOSITORY_USERNAME_1}", "password": "${env.REPOSITORY_TOKEN_PASS_1}" },
            { "id": "private_repository_2", "username": "${env.REPOSITORY_USERNAME_2}", "password": "${env.REPOSITORY_TOKEN_PASS_2}" }
          ]
    # Submit the dependency
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v1
```
