### ISSUE TITLE
Unable to locate executable file: mvnw

### ISSUE THREAD

**Issue by amal-stack** [advanced-security/maven-dependency-submission-action#27]
With the default option `ignore-maven-wrapper: false`, the following error is raised when a wrapper file `mvnw` exists:
```
Warning: Error encountered executing maven: Unable to locate executable file: /home/runner/work/notebooksfx/notebooksfx/mvnw. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
The file `mvnw` exists but is not executable.
I had to explicitly make the Maven wrapper executable for it to work using:
```yaml
- name: Make mvnw executable
   run: chmod +x ${{ github.workspace }}/mvnw
- name: Maven Dependency Tree Dependency Submission
  uses: advanced-security/maven-dependency-submission-action@v3.0.0
```
*From https://github.com/amal-stack/notebooksfx/blob/master/.github/workflows/maven.yml.*

Setting `ignore-maven-wrapper: true` also works but then it does not use the wrapper file.
